// const cars: Car[] = [
//     // Your car data here
//       {
//         name: "Koenigsegg",
//         type: "Sport",
//         price: "$99.00",
//         fuel: "90L",
//         transmission: "Manual",
//         seats: "2 People",
//         image: "/car1.png",
//       },
//       {
//         name: "Nissan GT - R",
//         type: "Luxury",
//         price: "$150.00",
//         fuel: "80L",
//         transmission: "Automatic",
//         seats: "2 People",
//         image: "/car2.png",
//       },
//       {
//         name: "Rolls - Royce",
//         type: "Luxury",
//         price: "$100.00",
//         fuel: "80L",
//         transmission: "Automatic",
//         seats: "2 People",
//         image: "/Car2.png",
//       },
//       {
//         name: "Rolls - Royce",
//         type: "Luxury",
//         price: "$100.00",
//         fuel: "80L",
//         transmission: "Automatic",
//         seats: "2 People",
//         image: "/Car1.png",
//       },
//       {
//         name: "Rolls - Royce",
//         type: "Luxury",
//         price: "$100.00",
//         fuel: "80L",
//         transmission: "Automatic",
//         seats: "2 People",
//         image: "/Car2.png",
//       },
//       {
//         name: "Rolls - Royce",
//         type: "Luxury",
//         price: "$100.00",
//         fuel: "80L",
//         transmission: "Automatic",
//         seats: "2 People",
//         image: "/Car8.png",
//       },
//       {
//         name: "Rolls - Royce",
//         type: "Luxury",
//         price: "$100.00",
//         fuel: "80L",
//         transmission: "Automatic",
//         seats: "2 People",
//         image: "/Car9.png",
//       },
//       {
//         name: "Rolls - Royce",
//         type: "Luxury",
//         price: "$100.00",
//         fuel: "80L",
//         transmission: "Automatic",
//         seats: "2 People",
//         image: "/Car (3).png",
//       },
//       {
//         name: "Rolls - Royce",
//         type: "Luxury",
//         price: "$100.00",
//         fuel: "80L",
//         transmission: "Automatic",
//         seats: "2 People",
//         image: "/Car (4).png",
//       },
//       {
//         name: "Rolls - Royce",
//         type: "Luxury",
//         price: "$100.00",
//         fuel: "80L",
//         transmission: "Automatic",
//         seats: "2 People",
//         image: "/Car (5).png",
//       },
//       {
//         name: "Rolls - Royce",
//         type: "Luxury",
//         price: "$100.00",
//         fuel: "80L",
//         transmission: "Automatic",
//         seats: "2 People",
//         image: "/Car (6).png",
//       },
//       {
//         name: "Rolls - Royce",
//         type: "Luxury",
//         price: "$100.00",
//         fuel: "80L",
//         transmission: "Automatic",
//         seats: "2 People",
//         image: "/Car (7).png",
//       },